"""Core data contracts for Fraud-Spike Detector using Pydantic.

Preserves exact frozen nullability requirements:
- RiskScore.score: float | None
- AuditRecord.risk_score: float | None
- Alert.risk_score: float (non-nullable)

Severity Protocol (Section 14):
Severity is derived from documented deviation magnitude (M = |observed - expected| / robust_scale),
not manually asserted. GroundTruthEvent carries both the derived magnitude float and severity_level string.
Contradictory severity levels (e.g. M=4.5 with severity_level='LOW') are rejected.
"""

from datetime import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field, model_validator


def derive_severity_level(magnitude: float) -> str:
    """Derive severity level string from standardized deviation magnitude M (Section 14).

    LOW    : M < 2.0
    MEDIUM : 2.0 <= M < 4.0
    HIGH   : M >= 4.0
    """
    if magnitude < 2.0:
        return "LOW"
    elif magnitude < 4.0:
        return "MEDIUM"
    else:
        return "HIGH"


class Transaction(BaseModel):
    transaction_id: str
    timestamp: datetime
    merchant_id: str
    customer_id: str
    amount: float
    payment_method: str
    country: str
    device_id: str


class GroundTruthEvent(BaseModel):
    """Ground truth event generated by synthetic stream injection.

    Severity is derived from standardized deviation magnitude M = |observed - expected| / robust_scale.
    Contract carries magnitude (severity) and categorical level (severity_level).
    Contradictory severity levels are rejected.
    """
    event_id: str
    merchant_id: str
    anomaly_type: str
    start_time: datetime
    end_time: datetime
    severity: float  # Standardized deviation magnitude M
    severity_level: Optional[str] = None  # LOW, MEDIUM, HIGH
    parameters: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_and_populate_severity_level(self) -> "GroundTruthEvent":
        expected = derive_severity_level(self.severity)
        if self.severity_level is not None and self.severity_level != expected:
            raise ValueError(
                f"Contradictory severity_level '{self.severity_level}' provided for severity magnitude {self.severity}. Expected '{expected}'."
            )
        self.severity_level = expected
        return self


class FeatureSnapshot(BaseModel):
    merchant_id: str
    timestamp: datetime
    volume: float
    velocity: float
    amount_statistics: dict[str, float] = Field(default_factory=dict)
    unique_customers: int
    unique_devices: int
    data_quality: str


class BaselineSnapshot(BaseModel):
    merchant_id: str
    timestamp: datetime
    expected_values: dict[str, float] = Field(default_factory=dict)
    robust_scale: dict[str, float] = Field(default_factory=dict)
    history_count: int
    current_window_count: int
    evidence_state: str  # SUFFICIENT, DEGRADED, INSUFFICIENT


class RiskScore(BaseModel):
    score: Optional[float] = None  # Explicit float | None requirement
    confidence: float
    triggered_signals: list[str] = Field(default_factory=list)
    data_quality: str = "GOOD"


class Alert(BaseModel):
    alert_id: str
    merchant_id: str
    timestamp: datetime
    risk_score: float  # Explicit non-nullable float requirement
    confidence: float
    reason: str
    triggered_signals: list[str] = Field(default_factory=list)
    detector_version: str


class AuditRecord(BaseModel):
    audit_id: str
    alert_id: Optional[str] = None
    merchant_id: str
    timestamp: datetime
    risk_score: Optional[float] = None  # Explicit float | None requirement
    confidence: float
    features: dict[str, Any] = Field(default_factory=dict)
    baseline: dict[str, Any] = Field(default_factory=dict)
    triggered_signals: list[str] = Field(default_factory=list)
    detector_version: str
    data_quality_status: str


class EvaluationMetrics(BaseModel):
    """Core evaluation metrics result contract."""
    tp: int
    fp: int
    fn: int
    tn: Optional[int] = None
    precision: float
    recall: float
    f1_score: float
    mean_latency_seconds: Optional[float] = None
    matched_events: list[dict[str, Any]] = Field(default_factory=list)
    unmatched_alerts: list[str] = Field(default_factory=list)
    unmatched_events: list[str] = Field(default_factory=list)


class CalibrationResult(BaseModel):
    """Result contract for detector threshold calibration sweep."""
    selected_threshold: float
    calibrated_f1: float
    calibrated_precision: float
    calibrated_recall: float
    sample_count: int
    status: str  # SUCCESS, INSUFFICIENT_EVIDENCE, FALLBACK


class AblationVariantConfig(BaseModel):
    """Configuration for a single isolated ablation study variant."""
    variant_id: str
    description: str
    disable_ewma: bool = False
    persistence: int = 2
    cooldown_windows: int = 5
    feature_subset: Optional[list[str]] = None
    static_threshold: float = 3.5


class AblationResult(BaseModel):
    """Result contract comparing an ablation variant against the full pipeline control."""
    variant_id: str
    metrics: EvaluationMetrics
    delta_f1: float
    delta_precision: float
    delta_recall: float
    delta_latency_seconds: Optional[float] = None


class DriftConditionConfig(BaseModel):
    """Configuration for a single isolated drift characterization condition."""
    condition_id: str
    description: str
    changed_factor: str
    magnitude: float
    start_minute: float = 0.0
    duration_minutes: float = 60.0


class DriftResult(BaseModel):
    """Result contract comparing control vs drifted detector execution under statistical regime shift."""
    condition_id: str
    control_metrics: EvaluationMetrics
    drifted_metrics: EvaluationMetrics
    delta_f1: float
    delta_precision: float
    delta_recall: float
    delta_latency_seconds: Optional[float] = None
    adaptation_window_count: int
    false_alert_count: int


class FrozenDetectorConfig(BaseModel):
    """Immutable frozen detector configuration shared across holdout and characterization suites."""
    static_threshold: float = 3.5
    ewma_alpha: float = 0.3
    persistence: int = 2
    cooldown_windows: int = 5
    min_window_count: int = 5
    temporal_tolerance_seconds: float = 0.0
    detector_version: str = "1.0.0"


class EvasionConditionConfig(BaseModel):
    """Configuration for a single isolated adversarial evasion characterization condition."""
    condition_id: str
    description: str
    evasion_strategy: str
    changed_factor: str
    magnitude: float
    start_minute: float = 50.0
    duration_minutes: float = 30.0


class EvasionResult(BaseModel):
    """Result contract comparing control vs evasion detector execution under adversarial transformation."""
    condition_id: str
    control_metrics: EvaluationMetrics
    evasion_metrics: EvaluationMetrics
    delta_f1: float
    delta_precision: float
    delta_recall: float
    delta_latency_seconds: Optional[float] = None
    detection_degraded: bool
    evasion_success_rate: float  # 1.0 = successful evasion (GT exists & no alert emitted), 0.0 = failed evasion

    # Score & state machine trajectory evidence required by protocol
    control_max_raw_score: float
    control_max_ewma_score: float
    control_score_ge_threshold: bool
    control_persistence_satisfied: bool
    control_alert_emitted: bool

    evasion_max_raw_score: float
    evasion_max_ewma_score: float
    evasion_score_ge_threshold: bool
    evasion_persistence_satisfied: bool
    evasion_alert_emitted: bool






