"""Core data contracts for Fraud-Spike Detector using Pydantic.

Preserves exact frozen nullability requirements:
- RiskScore.score: float | None
- AuditRecord.risk_score: float | None
- Alert.risk_score: float (non-nullable)

Severity Protocol (Section 14):
Severity is derived from documented deviation magnitude (M = |observed - expected| / robust_scale),
not manually asserted. GroundTruthEvent carries both the derived magnitude float and severity_level string.
"""

from datetime import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field, model_validator


def derive_severity_level(magnitude: float) -> str:
    """Derive severity level string from standardized deviation magnitude M (Section 14).

    LOW    : M < 2.0
    MEDIUM : 2.0 <= M < 4.0
    HIGH   : M >= 4.0
    """
    if magnitude < 2.0:
        return "LOW"
    elif magnitude < 4.0:
        return "MEDIUM"
    else:
        return "HIGH"


class Transaction(BaseModel):
    transaction_id: str
    timestamp: datetime
    merchant_id: str
    customer_id: str
    amount: float
    payment_method: str
    country: str
    device_id: str


class GroundTruthEvent(BaseModel):
    """Ground truth event generated by synthetic stream injection.

    Severity is derived from standardized deviation magnitude M = |observed - expected| / robust_scale.
    Contract carries magnitude (severity) and categorical level (severity_level).
    """
    event_id: str
    merchant_id: str
    anomaly_type: str
    start_time: datetime
    end_time: datetime
    severity: float  # Standardized deviation magnitude M
    severity_level: Optional[str] = None  # LOW, MEDIUM, HIGH
    parameters: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def populate_severity_level(self) -> "GroundTruthEvent":
        if self.severity_level is None:
            self.severity_level = derive_severity_level(self.severity)
        return self


class FeatureSnapshot(BaseModel):
    merchant_id: str
    timestamp: datetime
    volume: float
    velocity: float
    amount_statistics: dict[str, float] = Field(default_factory=dict)
    unique_customers: int
    unique_devices: int
    data_quality: str


class BaselineSnapshot(BaseModel):
    merchant_id: str
    timestamp: datetime
    expected_values: dict[str, float] = Field(default_factory=dict)
    robust_scale: dict[str, float] = Field(default_factory=dict)
    history_count: int
    current_window_count: int
    evidence_state: str  # SUFFICIENT, DEGRADED, INSUFFICIENT


class RiskScore(BaseModel):
    score: Optional[float] = None  # Explicit float | None requirement
    confidence: float
    triggered_signals: list[str] = Field(default_factory=list)
    data_quality: str = "GOOD"


class Alert(BaseModel):
    alert_id: str
    merchant_id: str
    timestamp: datetime
    risk_score: float  # Explicit non-nullable float requirement
    confidence: float
    reason: str
    triggered_signals: list[str] = Field(default_factory=list)
    detector_version: str


class AuditRecord(BaseModel):
    audit_id: str
    alert_id: Optional[str] = None
    merchant_id: str
    timestamp: datetime
    risk_score: Optional[float] = None  # Explicit float | None requirement
    confidence: float
    features: dict[str, Any] = Field(default_factory=dict)
    baseline: dict[str, Any] = Field(default_factory=dict)
    triggered_signals: list[str] = Field(default_factory=list)
    detector_version: str
    data_quality_status: str
